import fn from '../src';

describe('api.basic', () => {
  test('normail single value case', () => {
    const seq = 'MIRNKAFVVRLYPNAAQTELINRTLGSARFVY' +
      'NHFLARRIAAYKESGKGLTYGQTSSELTLLKQAEETSWLSEV' +
      'DKFALQNSLKNLETAYKNFFRTVKQSGKKVGFPRFRKKRTGE' +
      'SYRTQFTNNNIQIGEGRLKLPKLGWVKTKGQQDIQGKILNVT' +
      'VRRIHEGHYEASVLCEVEIPYLPAAPKFAAGVDVGIKDFAIV' +
      'TDGVRFKHEQNPKYYRSTLKRLRKAQQTLSRRKKGSARYGKA' +
      'KTKLARIHKRIVNKRQDFLHKLTTSLVREYEIIGTEHLKPDN' +
      'MRKNRRLALSISDAGWGEFIRQLEYKAAWYGRLVSKVSPYFP' +
      'SSQLCHDCGFKNPEVKNLAVRTWTCPNCGETHDRDENAALNI' +
      'RREALVAAGISDTLNAHGGYVRPASAGNGLRSENHATLVV';

    const result = fn(seq);
    expect(result.head).toEqual([
      1, 61, 121, 181,
      241, 301, 361
    ]);

    expect(result.body.length).toEqual(7);

    expect(result.tail).toEqual([
      60, 120, 180,
      240, 300, 360,
      420
    ])
  });
});
